require(['jquery','core/log','core/notification','core/str'],function($,log,Notification,str){var SesskeyCheck=function(){var me=this;this._errorshown=!1;this._str_title='Problem with this page';this._str_content='There is a problem with this page. Please, reload it in order to solve it.';this._str_reloadpage='Reload page';this._str_cancel='Cancel';str.get_strings([{key:'sesskeyinvalidsesskey',component:'theme_uji'},{key:'sesskeytitle',component:'theme_uji'},{key:'reloadpage',component:'theme_uji'},{key:'cancel',component:'theme_uji'}]).done(function(langStrings){me._str_title=langStrings[1];me._str_content=langStrings[0];me._str_reloadpage=langStrings[2];me._str_cancel=langStrings[3]})};SesskeyCheck.MIN_CHECK_TIME_MS=10000;SesskeyCheck.CHECK_WINDOW_MS=10000;SesskeyCheck.VALID_IDS=['page-blog-edit','page-mod-forum-post','page-mod-assign-mod','page-mod-dialogue-conversation','page-mod-quiz-attempt','page-mod-quiz-summary'];SesskeyCheck.prototype.isLoggedIn=function(){return!$('body').hasClass('notloggedin')};SesskeyCheck.prototype.isCheckablePage=function(){let pageid=$('body').attr('id');let pagefound;pagefound=SesskeyCheck.VALID_IDS.indexOf(pageid)!==-1;if(!pagefound){pagefound=/^page-mod-[^-]+-mod$/.test(pageid)}
return pagefound};SesskeyCheck.prototype.getPageSesskey=function(){return M.cfg.sesskey};SesskeyCheck.prototype.checkSesskey=function(sesskey){return $.ajax({url:M.cfg.wwwroot+'/theme/uji/ajax/sesskey_check.php',method:'POST',data:{'sesskey':sesskey}})};SesskeyCheck.prototype.scheduleNextCheck=function(){if(!this.isLoggedIn()||!this.isCheckablePage()){return}
if(this._lasttimeout){clearTimeout(this._lasttimeout)}
this._lasttimeout=setTimeout(this.onTimeCheck.bind(this),this.getNextCheckTime())};SesskeyCheck.prototype.getNextCheckTime=function(){return Math.floor(SesskeyCheck.MIN_CHECK_TIME_MS+Math.random()*SesskeyCheck.CHECK_WINDOW_MS)};SesskeyCheck.prototype.onTimeCheck=function(){let me=this;this.checkSesskey(this.getPageSesskey()).then(function(data){if(data.loggedin===!1||data.sesskey===!1){me.showError(data.loggedin,data.sesskey)}else{me.scheduleNextCheck.bind(me)()}}).catch(function(){me.scheduleNextCheck.bind(me)()})};SesskeyCheck.prototype.showError=function(isloggedin,sesskeyisvalid){this._errorshown=!0;Notification.confirm(this._str_title,this._str_content,this._str_reloadpage,this._str_cancel,function(){location.reload(!0)})};$(document).ready(function(){var skc=new SesskeyCheck();skc.scheduleNextCheck()})});
require(['jquery','core/log','core/notification','core/str'],function($,log,Notification,str){var CourseScroll=function(){if(CourseScroll.isModulePage()){this.runOnModulePage()}else if(CourseScroll.isCoursePage()){this.runOnCoursePage()}else{this._cleanAllStorage()}};CourseScroll.prototype.runOnModulePage=function(){let courseModuleId=this._getCourseModuleId();let courseId=this._getCourseId();this._storeCurrentModule(courseModuleId,courseId);if(CourseScroll.isForumDiscussionPage()){if(window.location.hash){this.scrollTo(window.location.hash)}}}
CourseScroll.prototype._storeCurrentModule=function(coursemoduleid,courseid){sessionStorage.setItem('scroll-course-'+courseid+'-cmid',coursemoduleid)}
CourseScroll.prototype._getCourseModuleToScroll=function(courseid){return sessionStorage.getItem('scroll-course-'+courseid+'-cmid')}
CourseScroll.prototype._cleanStorage=function(courseid){sessionStorage.removeItem('scroll-course-'+courseid+'-cmid')}
CourseScroll.prototype._cleanAllStorage=function(){let claves=Object.keys(sessionStorage)}
CourseScroll.prototype._getCourseModuleId=function(){let bodyclasses=$('body').attr('class');const matches=bodyclasses.match(/ cmid-([0-9]+) /);return matches[1]}
CourseScroll.prototype._getCourseId=function(){let bodyclasses=$('body').attr('class');const matches=bodyclasses.match(/ course-([0-9]+) /);return matches[1]}
CourseScroll.prototype._obtenerOffsetEdicion=function(){let height=0;document.querySelectorAll('.section-modchooser').forEach((item)=>{height+=item.offsetHeight});return height}
CourseScroll.prototype.runOnCoursePage=function(){let courseid=this._getCourseId();let me=this;if(!window.location.hash){let coursemoduletoscroll=this._getCourseModuleToScroll(courseid);if(!coursemoduletoscroll){return}
this.scrollTo('#module-'+coursemoduletoscroll)}
this._cleanStorage(courseid)}
CourseScroll.prototype.scrollTo=function(elementselector){let element=$(elementselector)[0];if(element){let page=document.getElementById('page');let scrollY;if(page){scrollY=page.scrollTop}else{scrollY=0}
if(scrollY<=10){element.scrollIntoView()}}}
CourseScroll.isModulePage=function(){return $('body').hasClass('path-mod')&&($('body').attr('class').match(/ cmid-([0-9]+) /)!==null)}
CourseScroll.isCoursePage=function(){return $('body').hasClass('path-course-view')}
CourseScroll.isForumDiscussionPage=function(){return $('body').attr('id')==='page-mod-forum-discuss'}
CourseScroll.isApplicable=function(){return CourseScroll.isModulePage()||CourseScroll.isCoursePage()}
CourseScroll.init=function(){if(!CourseScroll.isApplicable()){return}
return new CourseScroll()}
if(document.readyState!=='loading'){var courseScroll=CourseScroll.init()}else{document.addEventListener("DOMContentLoaded",(e)=>{var courseScroll=CourseScroll.init()})}})